---
run:
  timeout: 1m
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: readonly
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  unique-by-line: true
