{{- if and .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "speedtest-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "speedtest-exporter.labels" . | nindent 4 }}
spec:
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.policyTypes }}
  policyTypes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  podSelector:
    matchLabels:
      {{- include "speedtest-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
