---
name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - "**/*.go"
      - "Dockerfile"
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-lint.yaml@main

  unit-tests:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main

  build-slim:
    uses: heathcliff26/ci/.github/workflows/build-container.yaml@main
    needs:
      - lint
      - unit-tests
    permissions:
      contents: read
      packages: write
    with:
      dockerfile: Dockerfile
      tag: slim
      tags: "type=raw,value=latest,enable={{is_default_branch}}"
      dry-run: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    secrets: inherit

  build-cli:
    uses: heathcliff26/ci/.github/workflows/build-container.yaml@main
    needs:
      - lint
      - unit-tests
    permissions:
      contents: read
      packages: write
    with:
      dockerfile: Dockerfile.cli
      tag: cli
      tags: ""
      dry-run: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    secrets: inherit
