---
name: "Editorconfig Check"

on:
  workflow_dispatch:
  push:
    branches: ["main", "renovate/*"]
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  check-editorconfig:
    uses: heathcliff26/ci/.github/workflows/editorconfig-check.yaml@main
    permissions:
      contents: read
